{% set name = "qhub" %}
{% set version = "0.3.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: e130cf34c138ce3f0d90cc2dab37e15db6a8c78648c9bc92e90dc2a451afbf40

build:
  number: 0
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - auth0-python
    - bcrypt
    - cloudflare
    - cookiecutter ==1.7.2
    - gitignore-parser ==0.0.8
    - pydantic
    - pynacl
    - ruamel.yaml

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
  requires:
    - pip

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - tylerpotts
    - costrouc
    - danlester
    - aktech
    - viniciusdc
    - iameskild
